rpi5: include: platform_def: increasing MMAP_REGIONS and XLAT_TABLES
Adding new xlat tables requires increasing max entries of both
XLAT_TABLES and MMAP_REGIONS because existing count is not enough and
may lead to the following assertion:

    VERBOSE: Read-only data region: 0xb000 - 0xd000
    ERROR:   mmap_add_region_check() failed. error -12
    ASSERT: lib/xlat_tables_v2/xlat_tables_core.c:793
    BACKTRACE: START: assert
    0: EL3: 0x242c
    1: EL3: 0x1244
    2: EL3: 0x4584
    3: EL3: 0x4510
    4: EL3: 0x78f0
    5: EL3: 0x2744
    6: EL3: 0x10d4
    BACKTRACE: END: assert

Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>
Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>